let porta='http://192.168.2.3:5002';
let portb='http://192.168.2.3:5001';
/*let porta='http://admin.integraltel.com/';
let portb='http://doctor.integraltel.com/';*/
/*let porta='http://admin.yaeherhealth.com/';
let portb='http://doctor.yaeherhealth.com/';*/
const api={
    getType:porta+'/api/TencentCosAccessTokenType',//获取文件上传type参数
    getUpload:porta+'/api/TencentCosAccessToken',//获取文件上传upload参数
    userLogin:porta+'/api/TokenAuth/Authenticate',//登录 
    getPerms:porta+'/api/YaeherUserModule',// 获取路由权限
    //loginOut:porta+'/api/member/user/logout',//退出登录
    personalGet:porta+'/api/personal/get',//获取个人资料详情
    baseParams:porta+'/api/YaeherParameterList',//基础参数获取
    clinicParams:portb+'/api/DoctorSchedulingType',//门诊类型参数获取
    labelRelative:porta+'/api/YaeherLabelListByCode',//获取对应标签
    /*****管理端*****/
    /***权限管理***/
    /*角色管理*/
    roleList:porta+'/api/YaeherRolePage',//用户列表
    roleDelete:porta+'/api/DeleteYaeherRole',//用户删除
    roleAdd:porta+'/api/CreateYaeherRole',//用户添加提交
    roleData:porta+'/api/YaeherRoleById',//用户编辑数据获取
    roleUpdate:porta+'/api/UpdateYaeherRole',//用户编辑提交
    getcheckId:porta+'/api/YaeherRoleModuleList',//用户权限获取
    setcheckId:porta+'/api/CreateYaeherRoleModule',//用户权限设置
    /*菜单管理*/
    menuList:porta+'/api/YaeherModuleList',//菜单列表
    menuDelete:porta+'/api/DeleteYaeherModule',//菜单删除
    menuAdd:porta+'/api/CreateYaeherModule',//菜单添加提交
    menuData:porta+'/api/ReleaseById',//菜单编辑数据获取
    menuUpdate:porta+'/api/UpdateYaeherModule',//菜单编辑提交
    menuRoot:porta+'/api/YaeherModuleUpperList',//上级模块获取
    /*人员管理*/
    userList:porta+'/api/YaeherUserPage',//人员列表
    userDelete:porta+'/api/DeleteYaeherUser',//人员删除
    userAdd:porta+'/api/CreateYaeherUser',//人员添加提交
    userData:porta+'/api/YaeherUserById',//人员编辑数据获取
    userUpdate:porta+'/api/UpdateYaeherUser',//人员编辑提交
    userGetrole:porta+'/api/YaeherUserRoleByUserID',//获取分配角色信息
    userUpdaterole:porta+'/api/CreateYaeherUserRole',//提交分配角色信息
    userRoleList:porta+'/api/WXRoleList',//获取平台角色
    /***系统参数***/
    /*系统参数*/
    systemList:porta+'/api/SystemParameterPage',//系统参数列表
    systemDelete:porta+'/api/DeleteSystemParameter',//系统参数删除
    systemAdd:porta+'/api/CreateSystemParameter',//系统参数添加提交
    systemData:porta+'/api/SystemParameterById',//系统参数编辑数据获取
    systemUpdate:porta+'/api/UpdateSystemParameter',//系统参数编辑提交
    /*医生参数*/
    doctorparamList:porta+'/api/DoctorParaSetPage',//医生参数列表
    doctorparamDelete:porta+'/api/DeleteDoctorParaSet',//医生参数删除
    doctorparamAdd:porta+'/api/CreateDoctorParaSet',//医生参数添加提交
    doctorparamData:porta+'/api/DoctorParaSetById',//医生参数编辑数据获取
    doctorparamUpdate:porta+'/api/UpdateDoctorParaSet',//医生参数编辑提交
    /*医生上下线设置*/
    doctorstatusList:porta+'/api/DoctorOnlineRecordPage',//医生上下线列表
    doctorstatusData:porta+'/api/DoctorOnlineRecordById',//医生上下线编辑数据获取
    doctorstatusUpdate:porta+'/api/UpdateDoctorOnlineRecord',//医生上下线编辑提交
    /*地区管理*/
    regionList:porta+'/api/AreaManagePage',//地区管理列表
    /*消息提醒*/
    newsList:porta+'/api/InterfaceSetPage',//消息提醒列表
    newsDelete:porta+'/api/DeleteInterfaceSet',//消息提醒删除
    newsAdd:porta+'/api/CreateInterfaceSet',//消息提醒添加提交
    newsData:porta+'/api/InterfaceSetById',//消息提醒编辑数据获取
    newsUpdate:porta+'/api/UpdateInterfaceSet',//消息提醒编辑提交
    /*提供服务*/
    serviceList:porta+'/api/InterfaceSetPage',//提供服务列表
    serviceDelete:porta+'/api/DeleteInterfaceSet',//提供服务删除
    serviceAdd:porta+'/api/CreateInterfaceSet',//提供服务添加提交
    serviceData:porta+'/api/InterfaceSetById',//提供服务编辑数据获取
    serviceUpdate:porta+'/api/UpdateInterfaceSet',//提供服务编辑提交
    /*对接接口*/
    portList:porta+'/api/InterfaceSetPage',//对接接口列表
    portDelete:porta+'/api/DeleteInterfaceSet',//对接接口删除
    portAdd:porta+'/api/CreateInterfaceSet',//对接接口添加提交
    portData:porta+'/api/InterfaceSetById',//对接接口编辑数据获取
    portUpdate:porta+'/api/UpdateInterfaceSet',//对接接口编辑提交
    /*短信发送*/
    noteList:porta+'/api/YaeherMessageRemindPage',//短信发送列表
    /*星级与标签*/
    labelstartList:porta+'/api/YaeherLabelConfigList',//星级与标签列表
    labelstartDelete:porta+'/api/DeleteYaeherLabelConfig',//星级与标签删除
    labelstartAdd:porta+'/api/CreateYaeherLabelConfig',//星级与标签添加提交
    labelstartData:porta+'/api/YaeherLabelConfigById',//星级与标签编辑数据获取
    labelstartUpdate:porta+'/api/UpdateYaeherLabelConfig',//星级与标签编辑提交
    /*微信个性化菜单*/
    wechatList:porta+'/api/YaeherConditionalMenuList',//微信个性化列表
    wechatDelete:porta+'/api/DeleteYaeherConditionalMenu',//微信个性化删除
    wechatAdd:porta+'/api/CreateYaeherConditionalMenu',//微信个性化添加提交
    wechatData:porta+'/api/YaeherConditionalMenuById',//微信个性化编辑数据获取
    wechatUpdate:porta+'/api/UpdateYaeherConditionalMenu',//微信个性化编辑提交
    wechatSend:porta+'/api/UpdateWecharMenu',//微信个性化编辑提交
    /*轮播图*/
    swiperList:porta+'/api/YaeherBannerPage',//轮播图列表
    swiperDelete:porta+'/api/DeleteYaeherBanner',//轮播图删除
    swiperAdd:porta+'/api/CreateYaeherBanner',//轮播图添加提交
    swiperData:porta+'/api/YaeherBannerById',//轮播图编辑数据获取
    swiperUpdate:porta+'/api/UpdateYaeherBanner',//轮播图编辑提交
    /*公众号消息模板*/
    WXNewsModelGet:porta+'/api/AchieveMessageTemplate',//获取
    WXNewsModelUpdate:porta+'/api/UpdateMessageTemplate',//修改
    WXNewsModelList:porta+'/api/MessageTemplatePage',//消息模板列表
    WXNewsModelData:porta+'/api/MessageTemplateById',//消息模板数据获取
    /*发送消息模板*/
    WXModelSendList:porta+'/api/SendMessageList',//发送消息列表
    WXModelSendDelete:porta+'/api/DeleteSendMessage',//发送消息删除
    WXModelSendAdd:porta+'/api/CreateSendMessage',//发送消息添加提交
    WXModelSendData:porta+'/api/SendMessageId',//发送消息编辑数据获取
    WXModelSendUpdate:porta+'/api/UpdateSendMessage',//发送消息编辑提交
    /*公众号消息发送记录*/
    WXNewsSendList:porta+'/api/WecharSendMessagePage',//公众号消息发送列表
    WXNewsSendDetail:porta+'/api/WecharSendMessageById',//公众号消息发送详情
    /*系统配置*/
    systemSetList:porta+'/api/SystemConfigsPage',//系统配置列表
    systemSetUpdate:porta+'/api/SystemConfigsManager',//系统配置修改
    systemSetData:porta+'/api/SystemConfigsById',//获取系统配置数据
    /***咨询管理***/
    /*咨询列表*/
    referList:portb+'/api/ConsultationPage',//咨询列表
    referReply:portb+'/api/CreateConsultationReply',//咨询回复提交
    phoneReply:portb+'/api/CreatePhoneReplyRecord',//电话回复
    referDetail:portb+'/api/ConsultationDetail',//咨询详情获取
    referDelete:portb+'/api/DeleteConsultation',//咨询删除
    referBack:portb+'/api/CreateRefundManage',//咨询退单
    referReson:portb+'/api/DoctorRefundManageType',//咨询退单理由
    referPartdoctor:porta+'/api/ClinicDetailList',//推荐医生信息获取
    cacheData:porta+'/api/GetReplyMemory',//缓存获取
    cacheUpdate:porta+'/api/ConsultReplyMemory',//缓存更新
    cacheDelete:porta+'/api/RemoveConsultReplyMemory',//缓存删除
    /*订单管理*/
    orderList:portb+'/api/OrderManagePage',//订单列表
    orderDetail:portb+'/api/OrderManageById',//订单详情获取
    /*支付记录*/
    payrecordList:portb+'/api/OrderTradeRecordPage',//支付列表
    payrecordDetail:portb+'/api/OrderTradeRecordById',//支付详情获取
    /*退单管理*/
    retreatList:portb+'/api/RefunOrderPage',//退单列表
    retreatDetail:portb+'/api/RefundManageById',//退单详情获取
    rebackupdate:portb+'/api/UpdateRefundManage',//退单状态更新
    /*医生快捷回复*/
    fastreplyList:porta+'/api/QuickReplyPage',//快捷回复列表
    fastreplyListnopage:porta+'/api/QuickReplyList',//快捷回复列表
    fastreplyDelete:porta+'/api/DeleteQuickReply',//快捷回复删除
    fastreplyAdd:porta+'/api/CreateQuickReply',//快捷回复添加
    fastreplyData:porta+'/api/QuickReplyById',//  快捷回复编辑数据获取
    fastreplyUpdate:porta+'/api/UpdateQuickReply',//快捷回复编辑提交
    /***科室与医生***/
    /*标签管理*/
    labelList:porta+'/api/LablePage',//标签管理列表
    doctorlabelListnopage:porta+'/api/DoctorLables',//医生标签管理列表
    labelListnopage:porta+'/api/LableList',//科室标签管理列表
    labelDelete:porta+'/api/DeleteLable',//标签管理删除
    labelAdd:porta+'/api/CreateLable',//标签管理添加提交
    labelData:porta+'/api/LableById',//  标签管理编辑数据获取
    labelUpdate:porta+'/api/UpdateLable',//标签管理编辑提交
    /*标签关联组*/
    labelgroupList:porta+'/api/RelationLabelGroupPage',//标签关联组列表
    labelgroupDelete:porta+'/api/DeleteRelationLabelGroup',//标签关联组删除
    labelgroupAdd:porta+'/api/CreateRelationLabelGroup',//标签关联组添加提交
    labelgroupData:porta+'/api/RelationLabelGroupByID',//标签关联组编辑数据获取
    labelgroupUpdate:porta+'/api/UpdateRelationLabelGroup',//标签关联组编辑提交
    /*科室管理*/
    partList:porta+'/api/ClinicPage',//科室管理列表
    partListnopage:porta+'/api/ClinicList',//科室管理列表
    partDelete:porta+'/api/DeleteClinic',//科室管理删除
    partAdd:porta+'/api/CreateClinic',//科室管理添加提交
    partData:porta+'/api/ClinicById',//科室管理编辑数据获取
    partUpdate:porta+'/api/UpdateClinic',//科室管理编辑提交
    partGetlabel:porta+'/api/ClinicLableByClinicID',//科室管理默认标签获取
    partSetlabel:porta+'/api/CreateClinicAndLable',//科室管理标签提交
    partGetdoctor:porta+'/api/ClinicDoctorByClinicID',//科室管理默认医生获取
    partSetdoctor:porta+'/api/CreateClinicAndDoctor',//科室管理医生提交
    /*医生管理*/
    doctorList:portb+'/api/YaeherDoctorPage',//医生管理列表
    doctorListnopage:portb+'/api/YaeherDoctorList',//医生管理列表
    doctorDelete:portb+'/api/DeleteLable',//医生管理删除
    doctorDetial:portb+'/api/YaeherDoctorById',//医生管理详情获取
    doctorGetlabel:portb+'/api/DoctorRelationListByDoctorID',//医生管理默认标签获取
    doctorSetlabel:portb+'/api/CreateDoctorRelation',//医生管理标签提交
    doctorGetpart:portb+'/api/DoctorClinicListByDoctorID',//医生管理默认科室获取
    doctorSetpart:portb+'/api/CreateDoctorClinic',//医生管理科室提交
    doctorCheck:portb+'/api/AuthCheckYaeherDoctor',//医生审核
    /***个人中心***/
    /*系统文章管理*/
    articleList:porta+'/api/ReleaseManagePage',//文章管理列表
    articleDelete:porta+'/api/DeleteReleaseManage',//文章管理删除
    articleAdd:porta+'/api/CreateReleaseManage',//文章管理添加提交
    articleSend:porta+'/api/ReleaseArticle',//文章发布
    articleData:porta+'/api/ReleaseManageById',//文章管理编辑数据获取
    articleUpdate:porta+'/api/UpdateReleaseManage',//文章管理编辑提交
    /*医生文章管理*/
    doctorarticleList:portb+'/api/DoctorPaperPage',//文章管理列表
    doctorarticleDelete:portb+'/api/DeleteDoctorPaper',//文章管理删除
    doctorarticleAdd:portb+'/api/CreateDoctorPaper',//文章管理添加提交
    doctorarticleSend:portb+'/api/PushDoctorPaper',//文章推送
    doctorarticleData:portb+'/api/DoctorPaperById',//文章管理编辑数据获取
    doctorarticleUpdate:portb+'/api/UpdateDoctorPaper',//文章管理编辑提交
    /*问答管理*/
    answerList:porta+'/api/QuestionReleasePage',//问答管理列表
    answerDelete:porta+'/api/DeleteQuestionRelease',//问答管理删除
    answerAdd:porta+'/api/CreateQuestionRelease',//问答管理添加提交
    answerData:porta+'/api/QuestionReleaseById',//问答管理编辑数据获取
    answerUpdate:porta+'/api/UpdateQuestionRelease',//问答管理编辑提交
    /*制度管理*/
    regimeList:porta+'/api/DoctorRulesPage',//制度管理列表
    regimeDelete:porta+'/api/DeleteDoctorRules ',//制度管理删除
    regimeAdd:porta+'/api/CreateDoctorRules',//制度管理添加提交
    regimeData:porta+'/api/DoctorRulesByID',//制度管理编辑数据获取
    regimeUpdate:porta+'/api/UpdateDoctorRules',//制度管理编辑提交
    /*移动端权限分配*/
    mobileList:porta+'/api/YaeherUserPage',//移动端列表
    mobileData:porta+'/api/UserWecharRoleByUserID',//移动端全部权限数据获取
    mobileUpdate:porta+'/api/UpdateUserWXRole',//移动端编辑提交
    /*个人资料*/
    infoData:porta+'/api/YaeherUserById',//个人资料编辑数据获取
    infoUpdate:porta+'/api/UpdateYaeherUser',//个人资料编辑提交
    codeSend:porta+'/api/YaeherMessage',//发送验证码
    phoneUpdate:porta+'/api/UserAuthentication',//修改手机号码
    passUpdate:porta+'/api/ChangePassword',//修改密码
    infoallData:porta+'/api/YaeherUserDetailInfo',//个人资料获取
    /*质控委员*/
    qualityParam:porta+'/api/YaeherMobileParameterList',//获取质控参数
    qualityStatus:porta+'/api/QualityCommitteeByUser',//获取申请状态
    qualityApply:porta+'/api/CreateQualityCommitteeRegister',//申请或者取消质控
    /*从业经历*/
    workAdd:portb+'/api/CreateDoctorEmployment',//从业经历添加
    workDelete:portb+'/api/DeleteDoctorEmployment',//从业经历删
    workUpdate:portb+'/api/UpdateDoctorEmployment',//从业经历更新
    /*认证资料*/
    identityType:portb+'/api/YaeherDoctorAuthType',//获取认证类型
    identityAdd:portb+'/api/CreateDoctorFileList',//认证资料添加
    identityData:portb+'/api/DoctorDoctorFileApplyList',//认证资料编辑数据获取
    /*个人简历*/
    resumeApply:portb+'/api/UpdateYaeherDoctorResume',//个人简介提交
    /*标签添加*/
    tagAdd:porta+'/api/CreateLable',//标签添加
    //tagList:porta+'/api/DoctorLables',//标签列表
    tagData:porta+'/api/LablePage',//已添加标签
    tagDelete:portb+'/api/DeleteDoctorRelation',//标签删除
    /*科室管理*/
    doctorclinicList:portb+'/api/DoctorClinicApplyOut',//科室列表
    clinicAllList:porta+'/api/DoctorOutClinicList',//获取所有科室
    clinicPutImg:portb+'/api/DoctorFileApply',//图片信息提交
    doctorclinicAdd:portb+'/api/DoctorClinicApply',//科室添加
    doctorclinicData:portb+'/api/DoctorClinicApplyById',//科室数据获取
    doctorclinicUpdate:porta+'/api/UpdateDoctorClinicApply',//科室更新
    /*质控委员审核*/
    qualitycheckList:porta+'/api/QualityCommitteeRegisterPage',//质控委员审核列表
    qualitycheckData:porta+'/api/QualityCommitteeRegisterById',//质控委员详细信息
    qualitycheckPut:porta+'/api/QualityCommittee',//质控委员审核提交
    /*科室审核*/
    cliniccheckList:portb+'/api/DoctorClinicApplyPage',//科室审核列表
    cliniccheckPut:portb+'/api/UpdateDoctorClinicApply',//科室审核提交
    /*收入查看*/
    incomeList:portb+'/api/DoctorIncomePage',//收入查看列表
    incomeData:portb+'/api/DoctorIncomeByID',//收入查看数据获取
    /*排班设置*/
    arrangeList:portb+'/api/DoctorSchedulingPage',//排班设置列表
    arrangeDelete:portb+'/api/DeleteDoctorScheduling',//排班设置删除
    arrangeAdd:portb+'/api/CreateDoctorScheduling',//排班设置添加提交
    arrangeData:portb+'/api/DoctorSchedulingByID',//排班设置编辑数据获取
    arrangeUpdate:portb+'/api/UpdateDoctorScheduling',//排班设置编辑提交
    /*病例夹*/
    collect:portb+'/api/CollectConsultation',//收藏咨询-病例夹
    caseList:portb+'/api/CollectConsultationPage',//病例夹列表
    /*我的评价*/
    appraiseList:portb+'/api/ConsultationEvaluationPage',//我的评价列表
    appraiseData:portb+'/api/ConsultationEvaluationById',//评价详情
    /*咨询设置*/
    consultsetList:portb+'/api/ServiceMoneyList',//咨询设置列表
    consultsetParam:portb+'/api/ServiceMoneyListType',//咨询设置类型
    consultsetData:portb+'/api/ServiceMoneyListByID',//获取数据
    consultsetAdd:portb+'/api/CreateServiceMoneyList',//咨询设置添加
    consultsetUpdate:portb+'/api/UpdateServiceMoneyList',//咨询设置修改
    /*我的消息*/
    messageunRead:porta+'/api/UnReadyWecharList',//未读消息
    messageList:porta+'/api/AcceptWecharStatePage',//查询当前聊天状态
    messageData:porta+'/api/AcceptWecharStateId',//根据聊天查询聊天记录
    messageSend:porta+'/api/SendWechaMessgae',//发送消息
    messageTop:porta+'/api/UpdateWecharState',//消息置顶
    messageJoinin:porta+'/api/JoinWecharState',//点击用户发送消息
    /*收款方式设置*/
    incomesetList:porta+'/api/YaeherUserPaymentPage',//收款方式设置
    incomesetUpdate:porta+'/api/UpdateYaeherUserPayment',//收款方式设置
    bankcardAdd:porta+'/api/CreateYaeherUserPayment',//添加银行卡
    bankcardUpdate:porta+'/api/UpdateYaeherUserPayment',//修改银行卡
    /***统计报表***/
    ordercountList:porta+'/api/ConsultationOrderTotalInPage',//订单统计
    //incomeList:portb+'/api/DoctorIncomePage',//收入查看
    companyincomeList:portb+'/api/DoctorIncomePage',//公司收入查看
    appraisecountList:porta+'/api/EvaluationTotalPage',//评价统计
    rebackcountList:portb+'/api/RefundManagePage',//退单统计
    transferrecordList:porta+'/api/DoctorWithdrawRecordPage',//转账记录
    flowList:porta+'/api/AdminFlowReport',//流量查看
    /***质控管理***/
    chargepersonList:porta+'/api/QualityCommitteePage',//质控人员列表
    chargepersonAdd:porta+'/api/CreateQualityCommittee',//质控人员添加
    chargepersonDelete:porta+'/api/DeleteQualityCommittee',//质控人员删除
    chargepersonData:portb+'/api/YaeherDoctorSearch',//获取医生列表
    chargeorderList:porta+'/api/QualityEvaluationPage',//质控订单
    chargedoctororderList:portb+'/api/QualityControlManagePage',//质控委员订单
    chargedoctororderview:portb+'/api/QualityControlManageDetail',//质控委员订单详情
    chargedoctorput:portb+'/api/QualityControlManage',//质控委员评价提交
    appraiseview:portb+'/api/ConsultationEvaluationById',//评价详情
    chargeappraise:portb+'/api/UpdateConsultationEvaluation',//质控评分
    chargedoctor:portb+'/api/CreateQualityControlManage',//订单转给质控委员
    complainList:portb+'/api/QualityConsultationPage',//订单转给质控委员
    /***系统应用***/
    systemlogList:porta+'/api/YaeherOperListPage',//系统操作日志
    doctorlogList:porta+'/api/DoctorOnlineSetLogPage',//医生设置日志查看
    articlelogList:porta+'/api/ArticleOperPage',//文章问答操作日志

}




export default api;


